openapi: 3.0.4
info:
  title: Cart API
  version: v1
paths:
  /carts:
    post:
      tags:
        - Carts
      operationId: InitializeCart
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitializeCartRequest'
        required: true
      responses:
        '201':
          description: Cart is successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitializeCartResponse'
        '404':
          description: The user was not found.
  '/carts/{cartId}/items':
    post:
      tags:
        - Carts
      operationId: AddItemToCart
      parameters:
        - name: cartId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddItemToCartRequest'
        required: true
      responses:
        '201':
          description: Item is successfully added to the cart.
        '404':
          description: Either the cart, product, or user was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddItemToCartNotFoundResponse'
        '409':
          description: The item is already in the cart.
  '/carts/{cartId}':
    get:
      tags:
        - Carts
      operationId: GetCart
      parameters:
        - name: cartId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: The cart with the supplied ID.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: The cart with the supplied ID was not found.
components:
  schemas:
    AddItemToCartRequest:
      type: object
      properties:
        productId:
          type: integer
          format: int32
        quantity:
          type: integer
          format: int32
      additionalProperties: false
    AddItemToCartNotFoundResponse:
      type: object
      properties:
        reason:
          enum:
            - CartNotFound
            - ProductNotFound
            - UserNotFound
          type: string
      additionalProperties: false
    Cart:
      type: object
      properties:
        cartId:
          type: integer
          format: int32
        userId:
          type: integer
          format: int32
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
      additionalProperties: false
    CartItem:
      type: object
      properties:
        productId:
          type: integer
          format: int32
        quantity:
          type: integer
          format: int32
      additionalProperties: false
    InitializeCartRequest:
      type: object
      properties:
        userId:
          type: integer
          format: int32
      additionalProperties: false
    InitializeCartResponse:
      type: object
      properties:
        cartId:
          type: integer
          format: int32
      additionalProperties: false