openapi: 3.0.4
info:
  title: Cart API
  version: v1
paths:
  /carts:
    post:
      tags:
        - Carts
      operationId: InitializeCart
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitializeCartRequest'
        required: true
      responses:
        '201':
          description: Cart is successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitializeCartResponse'
        '400':
          description: The request body is invalid.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: The user was not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: The server encountered an unexpected error.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/carts/{cartId}/items':
    post:
      tags:
        - Carts
      operationId: AddItemToCart
      parameters:
        - name: cartId
          in: path
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddItemToCartRequest'
        required: true
      responses:
        '201':
          description: Item is successfully added to the cart.
        '400':
          description: The request body is invalid.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Either the cart, product, or user was not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/AddItemToCartNotFoundResponse'
        '409':
          description: The item is already in the cart.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: The server encountered an unexpected error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/carts/{cartId}':
    get:
      tags:
        - Carts
      operationId: GetCart
      parameters:
        - name: cartId
          in: path
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
      responses:
        '200':
          description: The cart with the supplied ID.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '400':
          description: The request body is invalid.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: The cart with the supplied ID was not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: The server encountered an unexpected error.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    AddItemToCartRequest:
      type: object
      required:
        - productId
        - quantity
      properties:
        productId:
          type: integer
          format: int32
        quantity:
          type: integer
          format: int32
      additionalProperties: false
    AddItemToCartNotFoundResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
        - type: object
          required:
            reason:
          properties:
            reason:
              enum:
                - CartNotFound
                - ProductNotFound
                - UserNotFound
              type: string
    Cart:
      type: object
      properties:
        cartId:
          type: integer
          format: int32
        userId:
          type: integer
          format: int32
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
      additionalProperties: false
    CartItem:
      type: object
      properties:
        productId:
          type: integer
          format: int32
        quantity:
          type: integer
          format: int32
      additionalProperties: false
    InitializeCartRequest:
      type: object
      required:
        - userId
      properties:
        userId:
          type: integer
          format: int32
          minimum: 0
      additionalProperties: false
    InitializeCartResponse:
      type: object
      properties:
        cartId:
          type: integer
          format: int32
      additionalProperties: false
    ErrorResponse:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
          format: int32
        detail:
          type: string
        instance:
          type: string
        traceId:
          type: string
      additionalProperties: true
